### ISSUE TITLE
redirect to `epidemics` vignettes in "coming soon" sections

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/tutorials-late#13]
In https://epiverse-trace.github.io/tutorials-late/compare-interventions.html#comparing-scenarios we have coming soon sections filled in issues are reminders in #12 and #7 

we have the opportunity to redirect to pkg vignettes in the meantime. @adamkucharski @pratikunterwegs do you have any suggestions for this?

**Comment by pratikunterwegs** [comment]
Regarding #7, you could link to the [Ebola vignette](https://epiverse-trace.github.io/epidemics/articles/model_ebola.html), which covers a range of potential interventions.

#12 could be covered by a range of vignettes, but the [basic vaccination vignette](https://epiverse-trace.github.io/epidemics/articles/modelling_vaccination.html) is a good place to start.

**Comment by avallecam** [comment]
We aim to solve this in #19
