### ISSUE TITLE
add challenge on comparing interventions for the Ebola case study

### ISSUE THREAD

**Issue by amanda-minter** [epiverse-trace/tutorials-late#7]
in response to issue epiverse-trace/tutorials#54, add [challenge](https://github.com/epiverse-trace/tutorials/blob/299839d363b62d28f57dfa38449f5d2522ed05a0/episodes/compare-interventions.Rmd#L273) to `compare_interventions.Rmd` that compares intervention against counterfactual using Ebola as case study

**Comment by avallecam** [comment]
now in https://github.com/epiverse-trace/tutorials-late/blob/a1a4b7df745e90ed165de2816e04c69aa27b66c9/episodes/compare-interventions.Rmd#L268-L278
