### ISSUE TITLE
update uncertainty plot

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/tutorials-late#9]
@adamkucharski @pratikunterwegs wondering if this is one of the plots in the tutorial that we would like to show differently

this is the current one: https://epiverse-trace.github.io/tutorials-late/simulating-transmission.html#accounting-for-uncertainty

adapt from vignette: https://epiverse-trace.github.io/epidemics/articles/modelling_scenarios.html#passing-a-vector-of-transmission-rates

we may update the code from Map to purrr::map() on this one or later

**Comment by pratikunterwegs** [comment]
Thanks, yes - would be good to use the same plot as from the linked vignette.

**Comment by avallecam** [comment]
We aim to solve this in #19
